### ISSUE TITLE
[CLARIFY] Why is the invoicing address taken from the commercial partner?

### ISSUE THREAD

**Issue by aisopuro** [OCA/edi#104]
Regarding the module `base_ubl`:

In the code used to generate the customer section (the `AccountingCustomerParty`, the partner used for the address details is the partner's commercial partner, not the partner themselves.

We have noticed that this means that if the invoicing address is truly different from the company it is related to (perhaps the company has several different invoicing addresses), then the address selected onto the invoice is not respected: the invoice of the parent is used instead.

The decision is explicitly made [here](https://github.com/OCA/edi/blob/11.0/base_ubl/models/ubl.py#L170), but no comment or docstring has been supplied explaining why it is done like this.

The module was originally authored by @alexis-via : might he be able to shed some light on why things are done this way?

I am trying to figure out whether I need to hack some kind of patch into our own system or try to make a fix PR here. If this is the expected behaviour in the rest of the world, and I'd end up breaking everybody else's installations, I probably shouldn't go for it.

**Comment by alexis-via** [comment]
This decision to use the commercial partner may be discussed and I'm open to modification.
In e-invoicing, the postal address is not supposed to be so important because you're not supposed to send your XML file by post... but I can understand that it can be important for some people :)

**Comment by aisopuro** [comment]
Well in Finland at least, if you're dealing with big companies or governmental entities, it may be that the company has multiple different invoicing addresses, and sometimes these invoicing addresses aren't just physical addresses, but actually different E-invoicing addresses.

I feel like there might be a need for a setting that allows you to change the logic for what partner's data is used. But I'm honestly unsure where such a setting should live. Should it be a global setting, or a per-partner setting (like a boolean or selection that allows the user to say "I want you to take the details from the parent" or "I want you to take the details from this parrtner, even if it has a parent"). I'm unsure what the best way would be to implement this.

And I will freely admit that I... can't really exactly remember what this is about :sweat: sorry. So if no-one is interested in putting thought into this, I think it might be fair to close this.
