### ISSUE TITLE
invoice2data: store templates in database?

### ISSUE THREAD

**Issue by StefanRijnhart** [OCA/edi#117]
@alexis-via Instead of taking custom invoice2data templates from a directory on the Odoo serverś file system, did you consider storing the templates in the database and caching their contents? Would you be interested in this feature?

**Comment by hbrunn** [comment]
did you see https://github.com/OCA/edi/pull/21/files#diff-dacb319278273b6cbb1e56ab74bf3952R5 where I slipped in the module `invoice2data_template`? As the customer we made that for switched to a different product, I won't be developing this further, so you're welcome to yank from there what you need if it fits for you

**Comment by StefanRijnhart** [comment]
Ooh pretty! Thank you.

**Comment by alexis-via** [comment]
@StefanRijnhart What advantage would you get in storing invoice2data templates in the DB rather than on the filesystem ? The ability for the user without access to the FS to add/modify an invoice2data template ? Another reason ?

**Comment by StefanRijnhart** [comment]
@alexis-via The reason is because sharing a directory with the Odoo server is never easy, and in my case it's not even allowed as per project policy. Plus you get all the benefit of managing the templates in the same systems as in which they are used, and Odoo access control and audit logging.

But if you don't see the benefit we will take Holger's work and use it as a customization in our system rather than pushing a PR.

**Comment by pedrobaeza** [comment]
I like your idea, @StefanRijnhart

**Comment by StefanRijnhart** [comment]
If we want to do this in the least disruptive way, we do not introduce a new dependency in account_invoice_import_invoice2data in a stable version, but we check at runtime if the module is installed and check any database templates in that case (in addition to the templates on the filesystem). When migrating this module to a new version, the explicit dependency can be added (add a comment about this in the module). Do you agree with this strategy?

**Comment by pedrobaeza** [comment]
OK for me.

**Comment by alexis-via** [comment]
@StefanRijnhart OK, I understand the reason. I think we can add this feature directly in the account_invoice_import_invoice2data module.

**Comment by StefanRijnhart** [comment]
OK, thanks! I'll add it to the ticket in our backlog to create a PR for this.

**Comment by StefanRijnhart** [comment]
Closing as there are PRs
