### ISSUE TITLE
Cannot install module account Invoice UBL

### ISSUE THREAD

**Issue by davshafik** [OCA/edi#122]
### Here is the Error i am getting when trying to install  account Invoice UBL module on Odoo v8

ParseError: "ValidateError
Field(s) `arch` failed against a constraint: Invalid view definition

Error details:
Field `partner_ids` does not exist

Error context:
View `account_payment_partner.payment.order.create.form`
[view_id: 2090, xml_id: n/a, model: payment.order.create, parent_id: 1629]" while parsing /opt/odoo/odoo-server/addons/account_payment_partner/wizard/payment_order_create_view.xml:11, near
<record id="view_create_payment_order" model="ir.ui.view">
    <field name="name">account_payment_partner.payment.order.create.form</field>
    <field name="model">payment.order.create</field>
    <field name="inherit_id" ref="account_banking_payment_export.view_create_payment_order"/>
     <field name="arch" type="xml">
        <field name="invoice" position="after">
            <field name="payment_mode" attrs="{'invisible': [('invoice', '=', False)], 'required': [('invoice', '=', True)]}"/>
        <field name="partner_ids"/>
     </field>
    </field>
</record>

**Comment by pedrobaeza** [comment]
It should be something on your deployment, as it's properly deployed on OCA runbot. Please check that.
