### ISSUE TITLE
[BUG TZ] Issue date should (must) be a context timestamp

### ISSUE THREAD

**Issue by blaggacao** [OCA/edi#129]
Not 100% sure about this, but I assume the following would be superior to the current code:
```python
        issue_date.text = fields.Date.context_today(
            self.with_context(tz=self.company_id.partner_id.tz),
            fields.Datetime.to_datetime(self.date_invoice)
        ).strftime('%Y-%m-%d')
```

Maybe, this can also be mitigated by specifying the `IssueDate` in more detail. But usually it is sensible to emit the date in the TZ context of the document (including when TZ is specified).

**Comment by pedrobaeza** [comment]
And what is current code? Which version? Please put a PR and it will be discussed there, not in dangling issues without context.

**Comment by blaggacao** [comment]
The current code is:

```python
        issue_date.text = self.date_invoice.strftime('%Y-%m-%d')
```

I'm working still through this library, I plan to share first a global patch per mail and then individual PRs...

**Comment by pedrobaeza** [comment]
It's better to provide directly a PR with several commits per changeset, explaining in the commit message the why

**Comment by blaggacao** [comment]
Yes, of course. However, I first prepare the patch that works for my use case (deadlines, and stuff) and then, only if there is interest, I might invest the additional time to prepare proper patches. This issue is definitely in the queue. :wink:

**Comment by pedrobaeza** [comment]
What I want to say is that stop spamming more issues

**Comment by blaggacao** [comment]
Oh, you didn't say that.
The fact that several issues are dropping in in high numbers is due to the fact that I'm currently working heavily with this repository.

If that supposes any problem, please let me know and please explain yourself.
