### ISSUE TITLE
XBRL : Taxonomy builder (proposal)

### ISSUE THREAD

**Issue by tarteo** [OCA/edi#13]
# XBRL : Taxonomy builder

This proposal is about implementing a XBRL taxonomy builder into Odoo. The final goal is to be able to generate XBRL instance documents based on government taxonomies and taxonomies created by other companies. This means the solution has to be generic. But the first step will be to create an _Odoo layer_ on top of the XML (taxonomies etc.). An _Odoo layer_ (models) is IMO easier to use than XML and turns Odoo into a taxonomy builder.

**This proposal only covers the taxonomy builder.**

## Features

* Import taxonomies
* Edit taxonomies
* Export taxonomies
* Validating instances
* The module act as a technical interface for other modules

### Menu

The main menu item will be located in menu item 'Settings'.

### Graphical interface

No new widgets are needed to implement the functionalities; the graphical interface will consist of default Odoo GUI components.

## Security

To grant access to the taxonomy builder features, a group (res.groups) is needed (something like "Manage XBRL Taxonomies").

## Conceptual ERD

![image](https://cloud.githubusercontent.com/assets/10028499/22743216/d7d6b54c-ee19-11e6-9cb4-e8d370bf8d92.png)

### Explanation

All entities of the model are conceptual and will be converted to Odoo models. e.g. entity 'Taxonomy' will be converted to model 'xbrl.taxonomy'.

* Schema: XML Schema documents which are not taxonomies but are used by taxonomies.
* Resource: Abstract resource, other models inherit from it resulting in a concrete resource (e.g. label resource and reference resource). The inheritance can also be solved with the introduction of a field like 'type'. But I prefer inheritance because it is IMO neater. This tactic will be consistently used.

## Others

The technical name of the module will be **xbrl**.
Dimensions are missing in this model (no support for the XBRL Dimensions schema).

I would love to hear your suggestions, questions and comments.

**Comment by bosd** [comment]
Great conecpt!
Is there any news about this?
