### ISSUE TITLE
Mass export

### ISSUE THREAD

**Issue by bst-bhc** [OCA/edi#142]
module: account_invoice_ubl
version: 12.0

Hello,

I was wondering if it was possible to mass export the XML ?
For instance, select a batch of invoice, go to Action/Export. 
I couldn't find the feature.

Thank you in advance for your answer,

Kind regards,

Benjamin

**Comment by OSevangelist** [comment]
@bst-bhc probably this isn't there yet. Did you check the code already for something like that
