### ISSUE TITLE
[12.0] Can't install module account_e-invoice_generate

### ISSUE THREAD

**Issue by Saran440** [OCA/edi#175]
Hello,

I create new database and install module `account_e-invoice_generate`
Error message :
`Modules "Account e-invoice Generate" and "Import Vendor Bills From XML" are incompatible.`
![Selection_004](https://user-images.githubusercontent.com/20896369/75221928-88068280-57d5-11ea-9419-933ce88e94e3.png)

What am I mistake?

Thank you.

**Comment by astirpe** [comment]
It's because module `account_e-invoice_generate` cannot be installed when standard module `account_facturx` is already installed. See https://github.com/OCA/edi/blob/12.0/account_e-invoice_generate/__manifest__.py#L15

You should uninstall `account_facturx` first.

**Comment by Saran440** [comment]
@astirpe Ahh, I see. Thank you very much :)

**Comment by Saran440** [comment]
@astirpe Sorry for reopen.
I test this issue again by new database. it's error, when database is not install module `account_facturx` before.

Step to error :
1. Create new database (with demo data)
2. Install module `account_e-invoice_generate`

But when I install module `account_facturx` and uninstall, After that I can install module `account_e-invoice_generate`.
Is it step normal?

**Comment by astirpe** [comment]
I agree with you that it's not a nice behavior.
On the other hand, this is the way the ['excludes': ['account_facturx']](https://github.com/OCA/edi/blob/12.0/account_e-invoice_generate/__manifest__.py#L15) line is supposed to work.

I think @alexis-via had good reasons for making that change, let's see if he wants to add any comments on this.

**Comment by alexis-via** [comment]
I made the change recently in this PR https://github.com/OCA/edi/pull/169
With this change, the PDF attachment of the invoice is stored with the XML data; if attachment_use is True, when you print the invoice again, it will NOT regenerate the XML, it will give you the original PDF file with the original XML attachment.
Unfortunately, it was not possible to implement that without removing the module account_facturx of Odoo SA.

**Comment by yucer** [comment]
Hello @alexis-via , but you are not using *runbot* or the unit tests for those PRs right ?

That change was merged without tests ? Is this problem with *account_facturx* the reason for that ?

I guess that some kind of exclusion should be done for the module *account_facturx*, because it is marked as *autoinstall* by Odoo.

**Comment by yucer** [comment]
> @astirpe Sorry for reopen.
> I test this issue again by new database. it's error, when database is not install module `account_facturx` before.
> 
> Step to error :
> 
>     1. Create new database (with demo data)
> 
>     2. Install module `account_e-invoice_generate`
> 
> 
> But when I install module `account_facturx` and uninstall, After that I can install module `account_e-invoice_generate`.
> Is it step normal?

That is because the module *account_facturx* is installed by default in a new database (autoinstall: True)

The first time you create the database you need to uninstall it.
