### ISSUE TITLE
which invoice2data ?

### ISSUE THREAD

**Issue by yucer** [OCA/edi#177]
This is just a request for info...

Which *invoice2data* external library is being used by *travis*? The one from [akretion](https://github.com/akretion/invoice2data) (5 years without changes) or the one from [invoice-x](https://github.com/invoice-x/invoice2data) (active recently) ?

The project [invoice2data](https://pypi.org/project/invoice2data/) registered in the python package index is the one from *invoice-x*, but I guess the code of the odoo addon uses the one from akretion / @alexis-via, because they made it.

Can somebody answer that ?

The code of *invoice-x* has now support for another input_readers (like tesseract4, etc..), I have verified that it works Ok with the v12 code of *account_invoice_import_invoice2data*.

Is that the one being installed ? I don't see that info in *.travis.yml*. How can we know which is the one being installed to test ?

The python dependency specified in the manifest has no from where is being installed, so I guess it is the one from the *python package index* (invoice-x).

**Comment by etobella** [comment]
The installed should come from pip, so invoice-x/invoice2data should be the one used.

https://pypi.org/project/invoice2data/
