### ISSUE TITLE
UBL inventory report and catalogue management

### ISSUE THREAD

**Issue by bealdav** [OCA/edi#179]
I have to work on these topics on UBL context (Odoo v8):

- Inventory Report (product stock in supplier warehouse)
- Prices and catalogue (exchange with suppliers)

My first module is Inventory Report but both module are with the same model `product.supplierinfo`.

I would like share opinions and experience on these topics with experts like @alexis-via @jbaudoux @lmignon @astirpe @wpichler or any other

Do you think I have to do one module depending the other or build modules strictly independent ?

For Inventory Report what module name should I choose ?

- supplier_stock_import_ubl
- ???

Only 2 fields for inventory report (supplier_stock_import_ubl) : stock_qty and last_stock (date)

docs:
- https://github.com/OCA/edi/blob/12.0/base_ubl/data/xsd-2.1/maindoc/UBL-InventoryReport-2.1.xsd (no difference with 2.2 version)
- https://github.com/Tradeshift/tradeshift-ubl-xsd/blob/master/src/test/resources/org/oasis-open/ubl/examples/UBL-InventoryReport-2.1-Example.xml

**Comment by jbaudoux** [comment]
Hello David,

Please look carefully at https://docs.peppol.eu/poacc/upgrade-3/ which is
the European standard for UBL data exchange. It clarifies the processes and
usage.
You will find some important information regarding the Catalogue.
Note also that Ordering and Despatch processes are currently being
developed  by lmi.
Inventory report is not part of peppol. Before implementing it, please look
deeply in peppol processes if you cannot use one of them as a replacement.

Kind regards
J-E

Le dim. 29 mars 2020 à 14:52, David Beal <notifications@github.com> a
écrit :

**Comment by bealdav** [comment]
Thanks for these informations

**Comment by bealdav** [comment]
#184 Inventory Report

**Comment by bealdav** [comment]
#184 is green and ready for review

**Comment by bealdav** [comment]
Now merged
