### ISSUE TITLE
Red branch because of use builtin names

### ISSUE THREAD

**Issue by bealdav** [OCA/edi#181]
Some branch are red because of code like here in v12

https://travis-ci.org/github/OCA/edi/jobs/663059314#L325-L328
```

base_ubl/models/ubl.py:57: [W0622(redefined-builtin), BaseUbl._ubl_add_address] Redefining built-in 'zip'

base_ubl/models/ubl.py:286: [W0622(redefined-builtin), BaseUbl._ubl_add_line_item] Redefining built-in 'type'

base_ubl/models/ubl.py:329: [W0622(redefined-builtin), BaseUbl._ubl_add_item] Redefining built-in 'type'

base_ubl/models/ubl.py:609: [W0622(redefined-builtin), BaseUbl.ubl_parse_address] Redefining built-in 'zip'

```
I propose to rename zip var or arg in zip_ and type in type_

It could break some method calls in case of named argument like here
https://github.com/OCA/edi/blob/12.0/base_ubl/models/ubl.py#L323-L329

but sure we'll at to fix it

What do you think ?

Thanks for sharing your ideas @astirpe @SimoRubi @lmignon @tarteo @alexis-via @joshuajan @feketemihai @acsonefho @rousseldenis @luc-demeyer @Cedric-Pigeon

**Comment by SimoRubi** [comment]
In my opinion, I'd rather rename the variables/arguments with something that explains their meaning.
In your example https://github.com/OCA/edi/blob/742b1316773f8a1b224e42c65c3c3a7685481a30/base_ubl/models/ubl.py#L323-L329
`type` could be renamed to `line_type` or something similar.

**Comment by astirpe** [comment]
@bealdav looking at the link to the travis log that you posted, it seems to me that the red branch is caused by the following error only:

```
************* Module account_e-invoice_generate

account_e-invoice_generate/readme/INSTALL.rst:6: [E7901(rst-syntax-error), ]  Duplicate explicit target name: "oca/edi".

------------


count_errors 1

pylint expected errors 0, found 1!
```

**Comment by bealdav** [comment]
You're right @astirpe 
pylint fixed by https://github.com/OCA/edi/pull/186
Could you merge ?

**Comment by bealdav** [comment]
OK green now, but we should note to not use builtin names in method for the future
