### ISSUE TITLE
EDI v8 red for an unknown reason, call to experts

### ISSUE THREAD

**Issue by bealdav** [OCA/edi#183]
I try to fix EDI v8 but I don't understand some messages

https://travis-ci.org/github/OCA/edi/jobs/670139063

`The command "sh -e /etc/init.d/xvfb start" failed and exited with 127 during .`

Which changes are required in travis or else

https://github.com/OCA/edi/pull/182

Please @sbidoul @gurneyalex @moylop260 could you have a look here. Thanks

**Comment by pedrobaeza** [comment]
Just remove that lines. The best thing is to check current .travis.yml template in MQT repo and put it here.

**Comment by bealdav** [comment]
This one ?
https://github.com/OCA/maintainer-quality-tools/blob/master/sample_files/.travis.yml

**Comment by pedrobaeza** [comment]
Yeah, that's it
