### ISSUE TITLE
[Question] Import company invoices

### ISSUE THREAD

**Issue by booo** [OCA/edi#24]
I have a bunch of invoices from my company and want to use the account_invoice_import module to import these old invoices of my company.

Is this possible with the current app? What is needed to make this possible? Can someone point me in the right direction?

Thanks for your help.

Best Philipp

**Comment by alexis-via** [comment]
This is currently not possible, because the module account_invoice_import only creates supplier invoices, and you want to create customer invoices. But with some modifications it could be possible.

**Comment by booo** [comment]
Do you have some hints on what needs some modifications?

**Comment by booo** [comment]
Do you think it's enough to set the invoice type to 'invoice_out' after I imported the invoice as supplier invoice to transform it to a customer invoice?

**Comment by alexis-via** [comment]
@booo it should work well now with my branch akretion/10-factur-x
You have an example that create a customer invoice in account_invoice_import/tests/test_invoice_import.py, method test_import_out_invoice(). It only works with "nline" invoice import methods.

**Comment by alexis-via** [comment]
@booo Are you happy with the implementation I made in my branch, cf my PR https://github.com/OCA/edi/pull/22 I did that for you, so I'd be glad to get your feedback.

**Comment by booo** [comment]
Thanks for all your work! I will try to take a closer look as soon as possible but I'm right now covered in other projects :/

In the meantime I implemented a "simple" and hackie solution with invoice2data and the xml api. I will try to post the code later on.
