### ISSUE TITLE
Installation of account_invoice_ubl with Error message

### ISSUE THREAD

**Issue by PSB24** [OCA/edi#245]
**module: account_invoice_ubl**
version: 13.0

**Steps to reproduce**
- New installation of odoo 13 community / installed apps are the following crm / stock / account / sale_management / purchase / contacts / mail
- uninstalled: account_facturx
- Copy of account_invoice_ubl in extra-addons

**Current behavior**
installing "Account Invoice UBL"  

Error message appears as follows:

_Something went wrong !
You try to install the module 'account_invoice_ubl' which has a dependency to the module 'account_tax_unece'.
But this necessary module cannot be installed._

The only place I´m able to find "account_tax_unece" to odoo 13 is https://pypi.org/project/odoo13-addon-account-tax-unece/13.0.1.0.1.dev4/ - but (I am not a professional!) I have no idea how to install it.

**Expected behavior**
Installation without error message, additionally required modules are installed if necessary.

**Comment by astirpe** [comment]
You can find module `account_tax_unece` (and it's needed dependency `base_unece`) here: https://github.com/OCA/community-data-files/tree/13.0
Click on button "Code" and then "Download Zip".
