### ISSUE TITLE
RFC Generic EDI framework

### ISSUE THREAD

**Issue by simahawk** [OCA/edi#249]
Me and @etobella have 2 similar implementations for defining EDI exchanges in a generic way and we decide to join the efforts.

The early raw roadmap is this:

1. have a generic EDI backend classified by type (#248)
2. describe exchanges by type or format (eg: outgoing vs incoming, needs a file, needs an ack, etc)
3. track exchanges w/ a generic record (either edi.exchange or edi.document) which will

* hold the data exchanged (being a file or other kind of data)
* hold the state (eg: sent, received, etc)
* not be responsible directly to generate the data

4. have a component mechanism to customize generation or parsing of data
5. have a templating system to define generation or parsing of data
6. have a component mechanism to talk to external protocols (using storage modules or api calls)
7. have generic hooks and events to customize what happens when records are received or sent
8. have a way to correlate exchanged records
 

@etobella please feel free to fix/adapt/extend :wink:

**Comment by max3903** [comment]
I have a customer that requires EDI 210, 810, 850 and 856 documents for version 14 and uses Ezcom (REST API).
Can I join the party?

**Comment by etobella** [comment]
Sure!!! The more the merrier 😄

**Comment by etobella** [comment]
@max3903 I just wanted to confirm that what we have created is not related with EDI X2 files, it is an standard framework for all kind of interchange of data between partners. It is perfect for the integration of EDI X2 protocols, but not already there. By the way, did you find any library to generate / read this kind of files? I found https://github.com/azoner/pyx12 but I don't know if it is fine.

**Comment by max3903** [comment]
@etobella No, and I don't think we will need to.

Our situation involves Bots (FTP) between Odoo and Ezcom (XML/RPC API) so my guess is that we would need to migrate the following modules:
* base_edi
* edi
* edi_xml
* edi_storage

and from other repos:
* storage_backend
* storage_backend_sftp

Am I missing something?

References:
* Bots: https://bots.readthedocs.io/en/latest/
* Ezcom: https://www.ezcomsoftware.com provides a REST and XML/RPC API. 
  * XML/RPC: https://www.myweborders.com/apidoc/
  * Rest: https://www.myweborders.com/restfuldoc/

**Comment by bealdav** [comment]
Nice to see a such activity on EDI repo.

Just a question from recent experience on EDI projects.
EDI implies exchange with other systems like ERP. All ERPs are not Odoo, not yet at least.
If you want maximize usage of EDI like UBL it could be more efficient to have an action to a level larger than Odoo.

Then I asked myself if we shouldn't move some parts of UBL from odoo module to python level.

Imagine you want implement UBL Order Response (or other flows) with your vendors. There is no existing toolbox to generate it easily then few suppliers will provide such files while

1/ all ERP have the same concept orders / order lines, product, qty, date, price
2/ all is implemented with an intense activity on Odoo side in this repo
3/ python can be integrate with many systems to interoperate with any db

Maybe we missed the opportunity to share our work in a larger ecosystem and get more contributions and have less duplication of code all those branch/odoo versions.

But perhaps, we could fill the gap in the future ?

What do you think ?

cc @lmignon @simahawk @Cedric-Pigeon @alexis-via @jgrandguillaume @yvaucher @jbaudoux @astirpe @hbrunn

**Comment by etobella** [comment]
@max3903 gr8. I didn't know this tool. It seems good and I think that with your proposal it might be enough :smile: Maybe you need `edi_account` or other modules that glues real models with edi mixin.

@bealdav About the usage as python level, I think it might have sense, but I don't know if the current creators are interested in this change :thinking:

**Comment by lmignon** [comment]
@bealdav You proposal makes sense and would be a great achievement but I wonder how you can do it..

**Comment by bealdav** [comment]
Thanks for your feedback

We can talk about it here https://github.com/OCA/edi/issues/314
cc @etobella @lmignon

**Comment by TeoGoddet** [comment]
Hi @simahawk 
What do you think of making possible to specify the processing python code for an exchange type on the exchange type (or better specify an action to execute) ?
