### ISSUE TITLE
Cannot install Account e-invoice Generate on Odoo CE V12

### ISSUE THREAD

**Issue by felixsniper** [OCA/edi#258]
Hi OCA,

I tried to test edi repository but I failed to installed it on Odoo CE V12.
When I tried to install "Account e-invoice Generate", it showed.

![image](https://user-images.githubusercontent.com/69030714/100093809-9bd93500-2e8a-11eb-89a2-e9f7a180cd7b.png)

Please help give me an advice,
Have a nice day,
Thanks,
Felix

**Comment by pedrobaeza** [comment]
That's because you have installed the module account_facturx from Odoo core, and both are incompatible. You have to remove one of them.

**Comment by nhoangvu** [comment]
Hi @pedrobaeza,

It worked.  
Thank you very much.

Regards,
Felix Nguyen.
