### ISSUE TITLE
Switch to MQT=PIP?

### ISSUE THREAD

**Issue by simahawk** [OCA/edi#276]
Anyone against?

**Comment by simahawk** [comment]
@bealdav @etobella @alexis-via ping :)

**Comment by bealdav** [comment]
+1 for pip at least on v14

**Comment by etobella** [comment]
No problem for me

**Comment by simahawk** [comment]
What about v13? I'd like to start from there. If not, at least we can use the new feature from setuptools odoo to generate requirements.txt automatically https://github.com/OCA/oca-addons-repo-template/pull/31/
I'll sync this repo w/ copier which will help w/ future updates as well.

**Comment by simahawk** [comment]
There we go https://github.com/OCA/edi/pull/277 (no switch yet)

**Comment by etobella** [comment]
Closing as the PR was merged
