### ISSUE TITLE
[12.0] account_invoice_import ATI amount only

### ISSUE THREAD

**Issue by Martronic-SA** [OCA/edi#293]
It seems that it's not possible to import an invoice where you have only the ATI amount (the amount to pay) but not the untaxed amount or the tax amount printed on the invoice, and you set a tax in the supplier import template.
If you dont have the untaxed amount, the import wizard will set _parsed_inv['amount_untaxed'] = parsed_inv['amount_total']_
but this fails later in post_process_invoice method when it compares the untaxed amount comupted in the newly created invoice with the parsed_inv['amount_untaxed'] *Amount untaxed difference found*. He tries to create a new adjustement line _prepare_global_adjustment_line which is wrong.

**Comment by yvaucher** [comment]
`account_invoice_import` was designed only with tax excluded in mind.

To fix this we will have to add the capability to use tax included. (This is a must have for Switzerland where most of the prices are tax included.)

**Comment by bosd** [comment]
There are some commits to implement ATI support in this V13 PR.
https://github.com/OCA/edi/pull/213
These have not been merged yet in V12,V13 or V14.

But there is an open PR for V10.
