### ISSUE TITLE
RFC create UBL document directly with python library

### ISSUE THREAD

**Issue by bealdav** [OCA/edi#314]
## Goal 

1. can be easily extract from any common erp system
2. can be easily mapped to convert in UBL: reduce implementation and maintenance cost.

### ideas :
- json structure: easy to produce with any langage and easy to get in python
- a flat csv file : not approved idea by OCA

### validation

EDIT

**Comment by etobella** [comment]
I think we should not invent anything and use UBL as it is, somehting like python-ubl. Then we can create all the necessary links. However, I am not sure which is the best approach for this.

On my experience with other standard protocols on other sectors, on my case, HL7 for Health environments. There was a standard library for Java (https://hapifhir.github.io/hapi-hl7v2/) that was really good, but, at the end, creating a workflow for a new customer or provider node was needed to be made manually as every time it had strange specifications.

**Comment by bealdav** [comment]
@etobella probably you're right about not invent anything.

But to build an UBL Xml we need to have an input.
Which is the most common data structure in any langage from which you can validate and create UBL Xml ?

Probably array, then json or dict ?


Here is some example of github lib but I don't evaluated them

https://github.com/glenfant/ubllib
https://github.com/frier17/python_ubl_impl

https://github.com/search?q=Universal+Business+Language

**Comment by etobella** [comment]
The more complete seems https://github.com/frier17/python_ubl_impl

But it still needs some work and the transformation to xml
