### ISSUE TITLE
Account e-invoice Generate, Settings option not visible

### ISSUE THREAD

**Issue by sohildesai-corigami** [OCA/edi#315]
I have installed an app into Odoo 13.0 community edition and still, I am not able to check the XML option in the section of "Electronic Invoices" at "Accounts > Configuration > Settings"

There are only two options available
1. false
2. None

Can you please help me to understand the feature?

**Comment by alexis-via** [comment]
If you install other modules such as account_invoice_ubl or account_invoice_facturx, you will have more values in the drop-down list.
