### ISSUE TITLE
Unable to install module "account_invoice_import_invoice2data": No module named invoice2data 

### ISSUE THREAD

**Issue by mhalmo** [OCA/edi#324]
Hello, 
I have installed Odoo v12 (bitnami installation package) on Ubuntu 20.04.
I am trying to install EDI module "account_invoice_import_invoice2data" (odoo v12), but unfortunatelly I have got error: because an external dependency is not met: No module named invoice2data.

When I run invoice2data commands from command line it is running without any problems and demo invoices are processed correctlly.

Please, any advace how to link external module to odoo12??

Thank you
BR
![obrázok](https://user-images.githubusercontent.com/17959208/107848408-8a515a80-6df3-11eb-99d1-ba5780965d9c.png)

![obrázok](https://user-images.githubusercontent.com/17959208/107848488-12376480-6df4-11eb-8156-e91415503372.png)

**Comment by pedrobaeza** [comment]
You have to install invoice2data python library.

**Comment by mhalmo** [comment]
I have installed it, take a look on screenshots

![obrázok](https://user-images.githubusercontent.com/17959208/107849025-ae636a80-6df8-11eb-8803-ecffbb92766f.png)

**Comment by pedrobaeza** [comment]
It seems that not in the environment where you are running Odoo.

**Comment by mhalmo** [comment]
Thx, I have got it...
