### ISSUE TITLE
Temporary dependencies in 14.0

### ISSUE THREAD

**Issue by simahawk** [OCA/edi#373]
@phuctranerp  this should not happen

https://github.com/OCA/edi/blob/14.0/test-requirements.txt

It's coming from https://github.com/OCA/edi/commit/fc0cfdd1d5de142314b90c9a62ea3ba21add2fdc

Can you fix it please? :pray: 

Thank you!

**Comment by phuctranfxvn** [comment]
Hi @simahawk

As I understand that, the path of `account_tax_unece` should be from `OCA/community-data-files` instead right ?
Actually, at the time the PR is done, the module `account_tax_unece` has not been migrated and merged into 14.0 yet.

Correct me if I am wrong

Thanks

**Comment by simahawk** [comment]
> As I understand that, the path of account_tax_unece should be from OCA/community-data-files instead right ?

[MQT=PIP is enabled in this repo](https://github.com/OCA/edi/blob/14.0/.travis.yml#L31) we don't need to reference other repos :wink: 

> Actually, at the time the PR is done, the module account_tax_unece has not been migrated and merged into 14.0 yet.

Yes, but we should never merge a PR if dependencies are not merged.

**Comment by phuctranfxvn** [comment]
I have submitted a PR for this fix here https://github.com/OCA/edi/pull/374
