### ISSUE TITLE
8.0 Travis red

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/edi#7]
@alexis-via, last merge has discovered several problems on Travis. Can you please fix them?

**Comment by alexis-via** [comment]
OK, but the pylint errors are not related to the latest merge, but to some new pylint rules that were not enabled before the merge.

**Comment by pedrobaeza** [comment]
I have also repaired Transifex with the commit https://github.com/OCA/edi/commit/1ced127801eb46581830377ce7254ee1d9b91426. Closing for now, although it would be good to have the requirements.txt file as said by @moylop260.
