### ISSUE TITLE
Question regarding OVH authentication

### ISSUE THREAD

**Issue by flotho** [OCA/edi#708]
Hi,

I would like to implement a connector for OVH here https://github.com/OCA/infrastructure/pull/18 and I'm wondering if there could be any interest into factorising the OVH API connector part.
As many modules are connecting to OVH API https://odoo-community.org/shop?search=ovh where could be the best place to have some modules like [provider]_api_authentication that will factorize the connexion process and could be used in other module. Could be used later for delivery carrier, bank provider etc...

Your proposal @pedrobaeza @alexis-via  @simahawk would be appreciated.

Regards

**Comment by pedrobaeza** [comment]
Not using them, sorry.

**Comment by flotho** [comment]
Hi @alexis-via , what is your advice regarding this part : https://github.com/OCA/edi/tree/14.0/account_invoice_download_ovh/wizard and https://github.com/OCA/edi/blob/14.0/account_invoice_download_ovh/models/account_invoice_download_config.py#L36

**Comment by alexis-via** [comment]
It is certainly a good idea! I think the wizard to connect to OVH API in account_invoice_import_download is pretty easy and user-friendly.
Also, we have to consider that, in about 2 years, we won't need this kind of connector any more in France (we'll connect to the PPF API), so account_invoice_import_download_ovh will probably not exist in v18... but it will still be useful for other countries.
