### ISSUE TITLE
account_invoice_ubl: Include XML file in mail

### ISSUE THREAD

**Issue by mgielissen** [OCA/edi#77]
Can the XML file included when sending mail?

**Comment by pedrobaeza** [comment]
Can you be a bit more specific?

**Comment by mgielissen** [comment]
When sending an invoice by mail, we have only the PDF file attached. Can the XML file automatically included, so we have 2 attachments (PDF and XML) in the invoice mail.

**Comment by pedrobaeza** [comment]
You aren't still saying which module.

**Comment by mgielissen** [comment]
My fault :P

account_invoice_ubl

**Comment by alexis-via** [comment]
With account_invoice_ubl, when sending a mail, you have 1 PDF attachment ; the XML file is embedded INSIDE the PDF file.

**Comment by mgielissen** [comment]
> 
> 
> With account_invoice_ubl, when sending a mail, you have 1 PDF attachment ; the XML file is embedded INSIDE the PDF file.

I understand that the XML file is embedded inside the PDF file. I've tested some Dutch accounting software. The problem was that they cannot read the embedded XML from the PDF file. The import works only when I manually generate the XML file.

**Comment by alexis-via** [comment]
ok, I understand. I don't think we should make it the default behavior, but it could be a config option to have the XML file added as attachment of the email, and add that feature in another small module that would depend on account_invoice_ubl. I think it should not be so difficult.

**Comment by CasVissers-360ERP** [comment]
@mgielissen Did you already solve this issue? I have a customer with the same requirement.

**Comment by mgielissen** [comment]
@CasVissers This not really an issue, more a added functionality.

**Comment by CasVissers-360ERP** [comment]
@mgielissen In that case, did you already worked on this added functionality?

**Comment by mgielissen** [comment]
@CasVissers Not yet, When the XML file is generated, the file is an attachment to the invoice. If the attachment could be added on the compose mail form (without downloading and uploading file).

**Comment by mgielissen** [comment]
@CasVissers Maybe this https://github.com/OCA/social/tree/12.0/mail_attach_existing_attachment_account

**Comment by CasVissers-360ERP** [comment]
@mgielissen 

> @CasVissers Maybe this https://github.com/OCA/social/tree/12.0/mail_attach_existing_attachment_account

This will require manual action by the user. I think I got budget to do this in a decent matter. Will let you know.
