### ISSUE TITLE
14.0 edi_oca synchronize ACK state with parent state when parent isn't processed by itself

### ISSUE THREAD

**Issue by simgonzalez** [OCA/edi#789]
**Is your feature request related to a problem?**
When I have an EDI link with an ACK I would except the ACK state to also update the parent exchange state if no processing behaviors is implemented for the parent exchange.

**Describe the solution you'd like**
The process state of the ACK exchange to define the process state of the parent exchange. 

**Describe alternatives you've considered**
To have a checkbox to activate or not that behavior.

**Additional context**
This could also be linked to update the state of the linked model. (That would need to implement a generic next_state method for all odoo model)

**Comment by ecino** [comment]
Can someone check this, as well as the PR that solves the issue?

**Comment by simahawk** [comment]
What do you mean exactly w/ "if no processing behaviors is implemented for the parent exchange"?
Can you give more details on your real use case?

**Comment by simgonzalez** [comment]
@simahawk hello,
I mean that in the EDI process (from what I understood, as there’s no documentation) the oca modules give a behavior until a standard done state but if we want the record to appear done and process (which seems to be the real final state) we have to implement a mixin to take care of our EDI Exchange record for our exchange type. Then what I mean is that when I have an ACK I except the ACK to take care of changing the final state for my original record. Except in the case where an implementation is done to process the original EDI exchange record.

The real use case concerns a bank SFTP where we upload file generated from payment orders those file are automatically uploaded to the SFTP and we except an ACK that will tell us if the bank successfully received the file.

available for any other details

**Comment by simahawk** [comment]
I see. Thanks for you explanation! I'll review and comment on the PR.
