### ISSUE TITLE
pdf_helper.: PDF file parsing failed: '/Names' 

### ISSUE THREAD

**Issue by bosd** [OCA/edi#825]
pdf_helper is always throwing an error, while working with a text / image based pdf as import.

## Describe the bug

The server log is polluted with ERROR lines which actually are no errors.
`2023-10-07 17:59:57,180 1787 ERROR odoo odoo.addons.pdf_helper.models.helper: PDF file parsing failed: '/Names' `

## To Reproduce
**Affected versions**:
14.0

1. Upload an pdf to any module which uses pdf_helper. Example `account_invoice_import_invoice2data`

**Expected behavior**
No error lines in the logger on standard functionality.

**Comment by pcastelovigo** [comment]
I can reproduce it, even if module works and passes tests.

**Comment by simahawk** [comment]
Yeah, I find it annoying too.
Reason: https://github.com/OCA/edi/blob/14.0/pdf_helper/models/helper.py#L26
For now I would simply switch it to debug.

**Comment by bosd** [comment]
Fix for V16 on it's way in: https://github.com/OCA/edi/pull/898
